In [16]:
import pandas as pd
import numpy as np
df = pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/wheat-seeds.csv')
dataset = df.values
X = dataset[:,0:6]
Y = dataset[:,7]

from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)
X_scale

from sklearn.model_selection import train_test_split
X_train, X_val_and_test, Y_train, Y_val_and_test = train_test_split(X_scale, Y, test_size=0.3)
X_val, X_test, Y_val, Y_test = train_test_split(X_val_and_test, Y_val_and_test, test_size=0.5)
print(X_train.shape, X_val.shape, X_test.shape, Y_train.shape, Y_val.shape, Y_test.shape)

(146, 6) (31, 6) (32, 6) (146,) (31,) (32,)


In [17]:
input_features = X_train
target_output = Y_train.reshape(146,1)

In [78]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_deriv(x):
    return sigmoid(x) * (1 - sigmoid(x))

def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

def tanh_deriv(x):
    return sigmoid(x) * (1 - sigmoid(x))

def relu(x):
    return np.maximum(0, x)

def relu_deriv(x):
    if x.any() < 0:
        return 0
    if x.any() >= 0:
        return 1

In [91]:
def run():
    #parameters
    weight_hidden = np.random.rand(6,6)
    weight_output = np.random.rand(6,6)
    lr = .001
    momentum_factor = .75 # gradient descent optimizer
    activation_function = sigmoid;
    af_derivative = sigmoid_deriv;
    
    for epoch in range(20):

        # set up initial variables
        hidden_layer_input = np.dot(input_features, weight_hidden)
        hidden_layer_output = activation_function(hidden_layer_input)
        output_layer_input = np.dot(hidden_layer_output, weight_output)
        output_layer_output = activation_function(output_layer_input)

        mse = ((1/2 * np.power((output_layer_output - target_output), 2)))
        #print(mse)

        first_derivative_error = output_layer_output - target_output
        out_over_in = af_derivative(output_layer_input)
        deriv_in_over_dwo = hidden_layer_output

        error_prod_dwo = np.dot(deriv_in_over_dwo.T, first_derivative_error * out_over_in)

        deriv_error_in = first_derivative_error * out_over_in
        deriv_in_out = weight_output
        derror_douth = np.dot(deriv_error_in, deriv_in_out.T)
        deriv_out_in = af_derivative(hidden_layer_input)
        deriv_input = input_features
        error_prod_wh = np.dot(deriv_input.T, deriv_out_in * derror_douth)

        weight_hidden = lr * error_prod_wh + (momentum_factor * weight_hidden)
        weight_output = lr * error_prod_dwo + (momentum_factor * weight_output)
    
run();

In [92]:
# print (weight_hidden)# Final output layer weight values :
# print (weight_output)# Predictions :#Taking inputs :
single_point = X_test[1]
#1st step :
result1 = np.dot(single_point, weight_hidden) 
#2nd step :
result2 = sigmoid(result1)
#3rd step :
result3 = np.dot(result2,weight_output)
#4th step :
result4 = sigmoid(result3)
print(result4)

[0.9353317  0.91272659 0.89055088 0.87906644 0.93130549 0.92600475]


In [93]:
# print (weight_hidden)# Final output layer weight values :
# print (weight_output)# Predictions :#Taking inputs :
single_point = Y_test[1]
#1st step :
result1 = np.dot(single_point, weight_hidden) 
#2nd step :
result2 = sigmoid(result1)
#3rd step :
result3 = np.dot(result2,weight_output)
#4th step :
result4 = sigmoid(result3)
print(result4)

[[0.91473654 0.88268687 0.86444842 0.85562723 0.90677962 0.90009745]
 [0.89539282 0.87560081 0.84271455 0.82599766 0.88448836 0.88098142]
 [0.90934033 0.88955651 0.85747201 0.84370164 0.90156921 0.89668978]
 [0.89884153 0.86646739 0.84947346 0.8489618  0.89875712 0.88941338]
 [0.90251045 0.86750558 0.85049356 0.83529208 0.89483525 0.88903555]
 [0.92168919 0.88404299 0.87192674 0.85564129 0.9028908  0.89623255]]
